version: '3'
services:
  dev-admin-cms-node:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    image: admin-cms/node:dev
    container_name: dev-admin-cms-node
    restart: unless-stopped
    tty: true
    ports:
      - '3002:3002'
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - app
networks:
  app:
    external: true
